---
title: "Supplement 2"
subtitle: "Sites of pain"
author: "Peter Kamerman" 
date: "Last knitted: `r format(Sys.Date(), '%d %B %Y')`"
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(skimr)
library(knitr)
library(boot)
library(broom)
library(patchwork)

# Outputs
options(scipen = 99999)

# Create figures folder
if(!dir.exists('figures')){
    dir.create('figures')
}

# Skimr options
skim <- skim_with(factor = sfl(ordered = NULL),
                  numeric = sfl(hist = NULL),
                  base = sfl(missing = n_missing,
                             complete = n_complete))

# Set knitr options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height = 6,
                      fig.width = 7,
                      fig.path = 'figures/supplement-2/')
```

----

# Import and check data

```{r import}
# Import
data <- read_rds('data-cleaned/data-pain-sites.rds')
demo <- read_rds('data-cleaned/data-demographics.rds')

# Check
## Pain sites 
dim(data)
names(data)
glimpse(data)

## Demographics
dim(demo)
names(demo)
glimpse(demo)
```

----

# Basic descriptive statistics

## Pain sites

```{r numerical_sites}
data %>% 
    select(-ID, -Site) %>% 
    mutate_if(is.character, factor) %>% 
    skim()
```

## Demographics

```{r numerical_demo}
demo %>% 
    select(-ID, -Site) %>% 
    select(Sex) %>% 
    mutate(Sex = factor(Sex)) %>% 
    skim()
```

----

# Boostrap function

```{r functions}
# Proportion
prop_func <- function(d, i){
    dat <- d[i, ]
    dat_vec <- dat[[1]]
    dat_prop <- mean(dat_vec == 'Yes', na.rm = TRUE)
    dat_prop
}
```

----

# Proportion with pain, by body site

Plotted as point estimates with bootstrapped 95% CIs

## Process data

```{r process_prop}
# Set seed
set.seed(2020)

# Remove ID and upper_back (only one outcome -- no pain) columns
prop <- data[, !(names(data) %in% c('ID', 'Upper_back'))]

# Bootstrap CIs
prop_boot <- prop %>% 
    # Remove Site column
    select(-Site) %>% 
    # Pivot to long format
    pivot_longer(cols = everything(),
                 names_to = 'body_site',
                 values_to = 'pain_present') %>% 
    # Add body regions
    mutate(region = case_when(
        body_site == 'Chest' |
            body_site == 'Head' |
            body_site == 'Throat' |
            body_site == 'Shoulder' ~ 'Head and upper torso',
        body_site == 'Lower_back' |
            body_site == 'Abdomen' |
            body_site == 'Hips' |
            body_site == 'Buttocks' |
            body_site == 'Groin' ~ 'Lower torso',
        body_site == 'Legs' |
            body_site == 'Knees' |
            body_site == 'Ankles.Feet' ~ 'Lower limbs',
        body_site == 'Arms' |
            body_site == 'Elbows' |
            body_site == 'Wrists.Hands' ~ 'Upper limbs',
        body_site == 'Cervical_spine' |
            body_site == 'Thoracic_spine' |
            body_site == 'Lumbosacral_spine' ~ 'Spinal column',
        TRUE ~ 'other'
    )) %>% 
    # Nest by body region and body site
    group_by(region, body_site) %>% 
    nest() %>% 
    # Boostrap data
    mutate(boot = map(.x = data,
                      ~ boot(data = .x,
                             statistic = prop_func, 
                             R = 999,
                             stype = 'i',
                             parallel = 'multicore',
                             ncpus = 4))) %>% 
    # Get CI
    mutate(ci = map(.x = boot,
                    ~ boot.ci(.x, type = 'perc'))) %>% 
    # Extract ci data
    mutate(point_est = map(.x = ci,
                           ~ .x$t0),
           lower_ci = map(.x = ci,
                          ~ .x$percent[[4]]),
           upper_ci = map(.x = ci,
                          ~ .x$percent[[5]])) %>% 
    # Remove columns
    select(-data, -boot, -ci) %>% 
    # Unnest
    unnest(cols = c(point_est, lower_ci, upper_ci))

# Re-nest by body region and generate figures and tables
prop_boot2 <- prop_boot %>% 
    group_by(region) %>% 
    nest() %>% 
    # Fix site labels
    mutate(data = map(.x = data,
                      ~ .x %>% 
                          mutate(body_site = str_replace_all(body_site,
                                                        pattern = '_',
                                                        replacement = ' '),
                                 body_site = str_replace_all(body_site, 
                                                        pattern = '\\.',
                                                        replacement = ' & '),
                                 body_site = str_replace_all(body_site,
                                                        pattern = 'Lower back',
                                                        replacement = 'Flank')))) %>% 
    # Re-order sites by point_est
    mutate(data = map(.x = data,
                      ~ .x %>% 
                          mutate(body_site = fct_reorder(body_site, 
                                                    point_est)))) %>% 
    # Plot data
    mutate(plots = map2(.x = data,
                        .y = region,
                       ~ .x %>% 
                           ggplot(data = .) +
                           aes(x = body_site,
                               y = point_est,
                               ymin = lower_ci,
                               ymax = upper_ci) +
                           geom_linerange(size = 1,
                                          colour = '#000000') +
                           geom_point(shape = 21,
                                      colour = '#000000',
                                      fill = '#000000',
                                      size = 3,
                                      stroke = 1) +
                           coord_flip() +
                            labs(title = .y,
                                 subtitle = '(Point estimate with 95%CI)',
                                 y = 'Proportion with pain') +
                            scale_y_continuous(limits = c(0, 0.6)) +
                            theme_minimal(base_size = 18) +
                            theme(plot.title = element_text(size = 18),
                                  plot.subtitle = element_text(size = 12),
                                  axis.title.y = element_blank(),
                                  panel.grid = element_blank(),
                                  axis.text = element_text(colour = '#000000'),
                                  axis.line = element_line(size = 0.5),
                                  axis.ticks = element_line(size = 0.5)))) %>% 
    # Tabulate data
    mutate(tables = map2(.x = data,
                         .y = region,
                         ~ .x %>% 
                             kable(caption = .y,
                                   digits = 2)))
```

## Tabulated data

```{r tabulated_prop, results = 'asis'}
walk(prop_boot2$tables, ~ print(.x))
```

## Plotted data

```{r plotted_prop}
walk(prop_boot2$plots, ~ print(.x))
```

----

# Proportion with pain, by body site and sex

Plotted as point estimates with bootstrapped 95% CIs.

## Process data

```{r process_sex}
# Set seed
set.seed(2020)

# Select sex data
sex <- demo[, c('ID', 'Sex')]

# Join to boot_data & remove ID, site, and upper_back (only one outcome -- no pain)
sex <- left_join(data, sex) %>% 
    select(-ID, -Site, -Upper_back)

# Bootstrap CIs
sex_boot <- sex %>% 
    # Pivot to long format
    pivot_longer(cols = -Sex,
                 names_to = 'body_site',
                 values_to = 'pain_present') %>% 
    # Add body regions
    mutate(region = case_when(
        body_site == 'Chest' |
            body_site == 'Head' |
            body_site == 'Throat' |
            body_site == 'Shoulder' ~ 'Head and upper torso',
        body_site == 'Lower_back' |
            body_site == 'Abdomen' |
            body_site == 'Hips' |
            body_site == 'Buttocks' |
            body_site == 'Groin' ~ 'Lower torso',
        body_site == 'Legs' |
            body_site == 'Knees' |
            body_site == 'Ankles.Feet' ~ 'Lower limbs',
        body_site == 'Arms' |
            body_site == 'Elbows' |
            body_site == 'Wrists.Hands' ~ 'Upper limbs',
        body_site == 'Cervical_spine' |
            body_site == 'Thoracic_spine' |
            body_site == 'Lumbosacral_spine' ~ 'Spinal column',
        TRUE ~ 'other'
    )) %>% 
    # Nest by body region and body site
    group_by(Sex, region, body_site) %>% 
    nest() %>% 
    # Boostrap data
    mutate(boot = map(.x = data,
                      ~ boot(data = .x,
                             statistic = prop_func, 
                             R = 999,
                             stype = 'i',
                             parallel = 'multicore',
                             ncpus = 4))) %>% 
    # Get CI
    mutate(ci = map(.x = boot,
                    ~ boot.ci(.x, type = 'perc'))) %>% 
    # Extract ci data
    mutate(point_est = map(.x = ci,
                           ~ .x$t0),
           lower_ci = map(.x = ci,
                          ~ .x$percent[[4]]),
           upper_ci = map(.x = ci,
                          ~ .x$percent[[5]])) %>% 
    # Remove columns
    select(-data, -boot, -ci) %>% 
    # Unnest
    unnest(cols = c(point_est, lower_ci, upper_ci))

# Re-nest by body region and generate figures and tables
sex_boot2 <- sex_boot %>% 
    group_by(region) %>% 
    nest() %>% 
    # Fix site labels
    mutate(data = map(.x = data,
                      ~ .x %>% 
                          mutate(body_site = str_replace_all(body_site,
                                                        pattern = '_',
                                                        replacement = ' '),
                                 body_site = str_replace_all(body_site, 
                                                        pattern = '\\.',
                                                        replacement = ' & ')))) %>% 
    # Re-order sites by point_est
    mutate(data = map(.x = data,
                      ~ .x %>% 
                          mutate(body_site = fct_reorder(body_site, 
                                                    point_est)))) %>% 
    # Plot data
    mutate(plots = map2(.x = data,
                        .y = region,
                       ~ .x %>% 
                           ggplot(data = .) +
                           aes(x = body_site,
                               y = point_est,
                               ymin = lower_ci,
                               ymax = upper_ci,
                               fill = Sex) +
                           geom_linerange(position = position_dodge2(width = 0.6),
                                          size = 1,
                                          colour = '#000000') +
                           geom_point(shape = 21,
                                      colour = '#000000',
                                      position = position_dodge2(width = 0.6),
                                      size = 4,
                                      stroke = 1) +
                           coord_flip() +
                           labs(title = .y,
                                subtitle = '(Point estimate with 95%CI)',
                                y = 'Proportion with pain') +
                           scale_y_continuous(limits = c(0, 0.6)) +
                           scale_fill_manual(values = c('#000000', '#FFFFFF')) +
                           theme_minimal(base_size = 18) +
                           theme(plot.title = element_text(size = 18),
                                 plot.subtitle = element_text(size = 12),
                                 legend.title = element_blank(),
                                 legend.position = c(0.8, 0.87),
                                 legend.background = element_rect(colour = '#000000',
                                                                  size = 0.3),
                                 axis.title.y = element_blank(),
                                 panel.grid = element_blank(),
                                 axis.text = element_text(colour = '#000000'),
                                 axis.line = element_line(size = 0.5),
                                 axis.ticks = element_line(size = 0.5)))) %>% 
    # Tabulate data
    mutate(tables = map2(.x = data,
                         .y = region,
                         ~ .x %>% 
                             arrange(body_site) %>% 
                             kable(caption = .y,
                                   digits = 2)))
```

## Tabulated data

```{r tabulated_sex, results = 'asis'}
walk(sex_boot2$tables, ~ print(.x))
```

## Plotted data

```{r plotted_sex}
# Individual plots
walk(sex_boot2$plots, ~ print(.x))
```

```{r publication_plot}
# Clean-up individual plots
sex_upper <- sex_boot2$plots[[1]] +
    theme(axis.title.x = element_blank(),
          plot.subtitle = element_blank(),
          legend.position = 'none')

sex_arm <- sex_boot2$plots[[2]] +
    theme(axis.title.x = element_blank(),
          plot.subtitle = element_blank(),
          legend.position = 'none')

sex_lower <- sex_boot2$plots[[3]] +
    theme(plot.subtitle = element_blank(),
          axis.title.x = element_blank())

sex_spine <- sex_boot2$plots[[4]] +
    theme(plot.subtitle = element_blank(),
          legend.position = 'none')

sex_leg <- sex_boot2$plots[[5]] +
    theme(plot.subtitle = element_blank(),
          legend.position = 'none')

# Organise individual plots
sex_prop <- sex_upper + sex_lower + sex_arm + sex_leg + sex_spine + 
    plot_layout(ncol = 2)

# Save plot
ggsave(filename = 'figures/figure_1.png', 
       plot = sex_prop,
       width = 12, 
       height = 12)
```

## Hypothesis testing

Fisher's Exact test for each body part. Family-wise error rate controlled using the Holm method.

```{r sex_hypothesis}
sex_long <- sex %>% 
    # Convert to long format
    pivot_longer(cols = -Sex,
                 names_to = 'body_part',
                 values_to = 'pain_present') %>% 
    # Nest by body part
    group_by(body_part) %>% 
    nest() %>% 
    # Tabulate sex ~ pain_present
    mutate(tab = map(.x = data,
                     ~ xtabs(~ Sex + pain_present, data = .x))) %>% 
    # Perform Fisher's Exact test
    mutate(fisher = map(.x = tab,
                        ~ tidy(fisher.test(.x)) %>% 
                            select(estimate, conf.low, conf.high, p.value) %>% 
                            rename(odds.ratio = estimate))) %>% 
    # Extract p-values
    mutate(p_value = map(.x = fisher,
                         ~ .x$p.value))

# Get adjusted p-value (Holm method)
body_part <- sex_long$body_part
p_value <- unlist(sex_long$p_value)
names(p_value) <- body_part
adjusted_p <- data.frame(p.value_holm = p.adjust(p_value, 
                                                     method = 'holm')) 
# Output
bind_rows(sex_long$fisher) %>% 
    bind_cols(data.frame(body.part = sex_long$body_part)) %>% 
    bind_cols(adjusted_p) %>% 
    select(body.part, everything()) %>% 
    arrange(p.value_holm) %>% 
    kable(caption = "Fisher's Exact test (Holm family-wise p-value correction)",
          digits = 3)
```

----

# Session information

```{r session}
sessionInfo()
```