---
title: "Supplement 1"
subtitle: "Demopgraphics"
author: "Peter Kamerman" 
date: "Last knitted: `r format(Sys.Date(), '%d %B %Y')`"
mainfont: Helvetica
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(skimr)
library(knitr)

# Create figures folder
if(!dir.exists('figures')){
    dir.create('figures')
}

# Skimr options
skim <- skim_with(factor = sfl(ordered = NULL),
                  numeric = sfl(hist = NULL))

# Set knitr options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height = 6,
                      fig.width = 7,
                      fig.path = 'figures/supplement-1/')
```

----

Note: Sites RBP and RISI removed at data cleaning stage because n < 10. 

----

# Import and check data

```{r import}
# Import
demo <- read_rds('data-cleaned/data-demographics.rds')

# Check
## Demographics
dim(demo)
names(demo)
glimpse(demo)
```

----

# Basic descriptive statistics

## Full cohort

### Descriptives

```{r numerical_sites}
demo %>% 
    # Remove ID column
    select(-ID) %>% 
    # Convert character to factor
    mutate_if(is.character, factor) %>% 
    skim()
```

## By site

### Sample size

```{r numerical_size}
demo %>% 
    # Select ID
    select(ID) %>% 
    # Clean-up ID column to keep only study site information
    mutate(ID = str_remove(ID, 
                           pattern = '[0-9][0-9]?[0-9]?[0-9]?')) %>%
    # Group data 
    group_by(ID) %>% 
    summarise(Count = n()) %>% 
    kable(caption = 'Sample size by study site')
```

### Descriptives

```{r numerical_demo}
demo %>% 
    # Clean-up ID column to keep only study site information
    mutate(ID = str_remove(ID, 
                           pattern = '[0-9][0-9]?[0-9]?[0-9]?')) %>%
    # Convert character to factor
    mutate_if(is.character, factor) %>% 
    # Group by site
    group_by(ID) %>%
    skim()
```

----

# Session information

```{r session}
sessionInfo()
```